# Project information
site_name: 나의 문서

# defeine TOC or order of website-
nav:
  - Home: index.md
  - Pages: 
    - level2:
      - level3:
        - level4:
          - first: pages/first.md

site_author: 윤형두
site_description: >-
  내 문서를 관리하는 곳
# Repository
repo_name: hdyoon93/my-docs
repo_url: https://github.com/hdyoon93/my-docs

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: ko
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/hdyoon93
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hdyoon93
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/hdyoon93
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/hdyoon93

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js#?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/hdyoon93"  target="_blank" rel="noopener">Hyungdoo Yoon</a>
